version: "3.8"
services:
 reverse-proxy:
    container_name: WitPaKul_Proxy
    image: nginx 
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Volume:/etc/nginx/conf.d
    
networks:
   default:
    external:
        name: witpakul_network
